exec-once = bash -c '[ -f ~/.config/hyprpeaz/hyprland.conf ] || mkdir -p ~/.config/hyprpeaz && touch ~/.config/hyprpeaz/hyprland.conf'
exec-once = bash -c '[ -f ~/.config/hyprpeaz/hyprland_generated.conf ] || mkdir -p ~/.config/hyprpeaz && touch ~/.config/hyprpeaz/hyprland_generated.conf'

source = ~/.cache/hyprpeaz/colors/colors-hyprland.conf

# Ensure local paths are set before sourcing other configs
env = HYPRPEAZ_ASSETS,/home/baris/.local/share/hyprpeaz/hyprpeaz-assets
env = HYPRPEAZ_LIB,/home/baris/.local/lib/hyprpeaz/hyprpeaz
env = PATH,$HOME/.local/bin:/usr/local/bin:/usr/bin

source = /home/baris/.local/share/hyprpeaz/hyprpeaz-assets/configs/hyprland/environment.conf
source = /home/baris/.local/share/hyprpeaz/hyprpeaz-assets/configs/hyprland/autostart.conf
source = /home/baris/.local/share/hyprpeaz/hyprpeaz-assets/configs/hyprland/decoration.conf
source = /home/baris/.local/share/hyprpeaz/hyprpeaz-assets/configs/hyprland/layout.conf
source = /home/baris/.local/share/hyprpeaz/hyprpeaz-assets/configs/hyprland/misc.conf
source = /home/baris/.local/share/hyprpeaz/hyprpeaz-assets/configs/hyprland/windowrule.conf
source = /home/baris/.local/share/hyprpeaz/hyprpeaz-assets/configs/hyprland/animation.conf
source = /home/baris/.local/share/hyprpeaz/hyprpeaz-assets/configs/hyprland/keybindings.conf

source = ~/.config/hyprpeaz/hyprland.conf
source = ~/.config/hyprpeaz/hyprland_generated.conf
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

exec-once = hyprpeaz-start
